//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursovaia.Logic.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant
    {
        public Applicant()
        {
            this.PROFESSION_SKILL = new HashSet<ProfessionSkill>();
            this.REFRESHERING = new HashSet<Refreshering>();
            this.HISTORY = new HashSet<History>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string FatherName { get; set; }
        public string LastWorkSpace { get; set; }
        public string Education { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Family { get; set; }
        public string SocialStatus { get; set; }
    
        public virtual ICollection<ProfessionSkill> PROFESSION_SKILL { get; set; }
        public virtual ICollection<Refreshering> REFRESHERING { get; set; }
        public virtual ICollection<History> HISTORY { get; set; }
    }
}
