//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursovaia.Logic.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WIN_Server : DbContext
    {
        public WIN_Server()
            : base("name=WIN_Server")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Applicant> Applicant { get; set; }
        public DbSet<Employee> Employee { get; set; }
        public DbSet<History> History { get; set; }
        public DbSet<Organization> Organization { get; set; }
        public DbSet<Profession> Profession { get; set; }
        public DbSet<ProfessionSkill> ProfessionSkill { get; set; }
        public DbSet<RefresherCours> RefresherCours { get; set; }
        public DbSet<Refreshering> Refreshering { get; set; }
        public DbSet<ShereProfession> ShereProfession { get; set; }
        public DbSet<Speciality> Speciality { get; set; }
        public DbSet<Vacancy> Vacancy { get; set; }
        public DbSet<VEmployee> V_EMPLOYEE { get; set; }
    }
}
