//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursovaia.Logic.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profession
    {
        public Profession()
        {
            this.VACANCY = new HashSet<Vacancy>();
            this.PROFESSION_SKILL = new HashSet<ProfessionSkill>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int IdShereProfession { get; set; }
    
        public virtual ShereProfession SHERE_PROFESSION { get; set; }
        public virtual ICollection<Vacancy> VACANCY { get; set; }
        public virtual ICollection<ProfessionSkill> PROFESSION_SKILL { get; set; }
    }
}
