//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursovaia.Logic.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VHistory
    {
        public int Id { get; set; }
        public int IdEmployee { get; set; }
        public int IdVacancy { get; set; }
        public int IdApplicant { get; set; }
        public int Status { get; set; }
        public System.DateTime DateAdd { get; set; }
        public string ApplicantFirstName { get; set; }
        public string ApplicantSecondName { get; set; }
        public string About { get; set; }
        public string NameOrganization { get; set; }
        public string NameProfession { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeeSecondName { get; set; }
        public int IdOrganization { get; set; }
    }
}
