//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursovaia.Logic.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VProfessionSkill
    {
        public int Id { get; set; }
        public int IdApplicant { get; set; }
        public int IdProfession { get; set; }
        public string NameProfession { get; set; }
    }
}
