//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursovaia.Logic.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VProfession
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int IdShereProfession { get; set; }
        public string NameShereProfession { get; set; }
    }
}
