//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursovaia.Logic.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.History = new HashSet<History>();
        }
    
        public int Id { get; set; }
        public int IdSpeciality { get; set; }
        public string FirsName { get; set; }
        public string SecondName { get; set; }
        public string FatherName { get; set; }
        public System.DateTime Birthday { get; set; }
    
        public virtual Speciality Spetialiry { get; set; }
        public virtual ICollection<History> History { get; set; }
    }
}
