//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursovaia.Logic.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refreshering
    {
        public int Id { get; set; }
        public int IdRefresherCours { get; set; }
        public int IdApplicant { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual Applicant APPLICANT { get; set; }
        public virtual RefresherCours RefresherCours { get; set; }
    }
}
