//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursovaia.Logic.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefresherCours
    {
        public RefresherCours()
        {
            this.Refreshering = new HashSet<Refreshering>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int DURATION { get; set; }
    
        public virtual ICollection<Refreshering> Refreshering { get; set; }
    }
}
