//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursovaia.Logic.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacancy
    {
        public Vacancy()
        {
            this.HISTORY = new HashSet<History>();
        }
    
        public int Id { get; set; }
        public int IdOrganization { get; set; }
        public int IdProfession { get; set; }
        public string About { get; set; }
        public bool Status { get; set; }
        public int MinExperience { get; set; }
        public int MaxExperience { get; set; }
        public System.DateTime AddDate { get; set; }
    
        public virtual ICollection<History> HISTORY { get; set; }
        public virtual Organization ORGANIZATION { get; set; }
        public virtual Profession PROFESSION { get; set; }
    }
}
